spring:
  application:
    name: config-server
      #增加消息队列的访问地址
  rabbitmq:
    host: 192.168.245.4
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/sunxu89/xdclass.git
          username: sunxu0809@qq.com
          password: q1q1q1

server:
   port: 9100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
